name: Get pull request information from the pull request number
description: Get pull request information from the pull request number
inputs:
  github_token:
    description: GitHub Access Token
    required: false
    default: ${{github.token}}
  number:
    description: pull request number
    required: false
    default: ${{github.event.number}}
  timeout:
    description: timeout
    required: false
    default: 60
  interval:
    description: interval
    required: false
    default: 5
outputs:
  pull_request:
    description: pull request
  merge_commit_sha:
    description: merge commit sha
runs:
  using: node20
  main: dist/index.js
