---
name: test
on: workflow_call
jobs:
  test:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3
        with:
          persist-credentials: false
      - uses: ./
        id: pr
      - run: echo "$PR"
        env:
          PR: ${{steps.pr.outputs.pull_request}}
      - run: echo "$SHA"
        env:
          SHA: ${{steps.pr.outputs.merge_commit_sha}}
